---
id: graduating-ruby-literal-object-generation-from-parsey
base_name: slide
tags:
- rabbit
presentation_date: 
presentation_start_time: 
presentation_end_time: 
version: 1.0.2
licenses: []
slideshare_id: 
speaker_deck_id: 
vimeo_id: 
youtube_id: 
width: 1600
height: 900
source_code_uri: 
author:
  markup_language: :markdown
  name: S.H.
  email: gamelinks007@gmail.com
  rubygems_user: S_H_
  slideshare_user: 
  speaker_deck_user: 
